import React from "react";
import { hydrate } from "react-dom";
import App from "./App";

// any other browser-only things...

// hydrate: light render...

// i expect markup to already be there...just take over what's there and don't render...

// render...i don't care what's in there...blow it up and put my stuff in...

// hmmm what's the difference...

hydrate(<App />, document.getElementById("root"));
